//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public Application()
        {
            this.AppAssignments1 = new HashSet<AppAssignments1>();
            this.AppAssignments3 = new HashSet<AppAssignments3>();
            this.AppConfigActions = new HashSet<AppConfigAction>();
            this.AppInfoValues = new HashSet<AppInfoValue>();
            this.AppSetAssignments = new HashSet<AppSetAssignment>();
            this.AppSiteConfigActions = new HashSet<AppSiteConfigAction>();
            this.Subprojects = new HashSet<Subproject>();
            this.Projects = new HashSet<Project>();
            this.Sites = new HashSet<Site>();
            this.ApplicationGroups = new HashSet<ApplicationGroup>();
        }
    
        public int AppID { get; set; }
        public string AppAbbr { get; set; }
        public string AppName { get; set; }
        public string AppDescription { get; set; }
        public string AppInvocation { get; set; }
        public string AltAppInvocation { get; set; }
        public string AppArgs { get; set; }
        public string AppToMonitor { get; set; }
        public string AppWorkingDir { get; set; }
        public string AppVersion { get; set; }
        public int AppType { get; set; }
        public int AccountingLevel { get; set; }
        public Nullable<int> SoftwarePublisherID { get; set; }
        public string Comment { get; set; }
    
        public virtual ICollection<AppAssignments1> AppAssignments1 { get; set; }
        public virtual ICollection<AppAssignments3> AppAssignments3 { get; set; }
        public virtual ICollection<AppConfigAction> AppConfigActions { get; set; }
        public virtual ICollection<AppInfoValue> AppInfoValues { get; set; }
        public virtual SoftwarePublisher SoftwarePublisher { get; set; }
        public virtual ICollection<AppSetAssignment> AppSetAssignments { get; set; }
        public virtual ICollection<AppSiteConfigAction> AppSiteConfigActions { get; set; }
        public virtual ICollection<Subproject> Subprojects { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<Site> Sites { get; set; }
        public virtual ICollection<ApplicationGroup> ApplicationGroups { get; set; }
    }
}
