//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppSetGUID
    {
        public AppSetGUID()
        {
            this.AppSetAssignments = new HashSet<AppSetAssignment>();
        }
    
        public int AppsetID { get; set; }
        public string GUID { get; set; }
        public string AppsetName { get; set; }
    
        public virtual ICollection<AppSetAssignment> AppSetAssignments { get; set; }
    }
}
