//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class GBU
    {
        public GBU()
        {
            this.GBUConfigActions = new HashSet<GBUConfigAction>();
            this.GBUInfoValues = new HashSet<GBUInfoValue>();
            this.GBUSysParameters = new HashSet<GBUSysParameter>();
            this.Projects = new HashSet<Project>();
            this.Sites = new HashSet<Site>();
        }
    
        public int GBUID { get; set; }
        public string GBUAbbr { get; set; }
        public string GBUName { get; set; }
        public string Comment { get; set; }
    
        public virtual ICollection<GBUConfigAction> GBUConfigActions { get; set; }
        public virtual ICollection<GBUInfoValue> GBUInfoValues { get; set; }
        public virtual ICollection<GBUSysParameter> GBUSysParameters { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<Site> Sites { get; set; }
    }
}
