//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupAssignments3
    {
        public int AppGroupID { get; set; }
        public int ProjID { get; set; }
        public int DiscID { get; set; }
    
        public virtual ApplicationGroup ApplicationGroup { get; set; }
        public virtual Discipline Discipline { get; set; }
        public virtual Project Project { get; set; }
    }
}
