//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftwarePublisher
    {
        public SoftwarePublisher()
        {
            this.Applications = new HashSet<Application>();
        }
    
        public int SoftwarePublisherID { get; set; }
        public string SoftwarePublisherName { get; set; }
        public string Comment { get; set; }
    
        public virtual ICollection<Application> Applications { get; set; }
    }
}
