//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemInfoValue
    {
        public string SystemInfoName { get; set; }
        public string SystemInfoValue1 { get; set; }
        public string SystemInfoDescription { get; set; }
        public string Comment { get; set; }
    }
}
