//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempOrg
    {
        public int Id { get; set; }
        public string site { get; set; }
        public string project { get; set; }
        public string subproj { get; set; }
        public string disc { get; set; }
    }
}
