//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobWbsAssignments1
    {
        public int ProjID { get; set; }
        public string Job { get; set; }
        public string WBS { get; set; }
        public string JobDescription { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
