//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjSiteAssignment
    {
        public int ProjID { get; set; }
        public int SiteID { get; set; }
        public string ProjDirname { get; set; }
        public string ProjDrive { get; set; }
        public string Servername { get; set; }
        public string Sharename { get; set; }
        public bool SharedAtProjDir { get; set; }
        public Nullable<int> CmpyStdID { get; set; }
        public string CmpyStdDrive { get; set; }
        public string ProjLinkPath { get; set; }
        public string ProjGEDir { get; set; }
        public string Comment { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Site Site { get; set; }
    }
}
