//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReplicationSource
    {
        public int SiteID { get; set; }
        public int ProjID { get; set; }
        public int SubpID { get; set; }
        public int DiscID { get; set; }
        public short ValidationResult { get; set; }
    }
}
