//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteInfoValue
    {
        public int SiteID { get; set; }
        public string SiteInfoName { get; set; }
        public string SiteInfoValue1 { get; set; }
        public string SiteInfoDescription { get; set; }
        public string Comment { get; set; }
    
        public virtual Site Site { get; set; }
    }
}
