//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Site()
        {
            this.AppGroupSiteConfigActions = new HashSet<AppGroupSiteConfigAction>();
            this.AppSiteConfigActions = new HashSet<AppSiteConfigAction>();
            this.JobWbsAssignments2 = new HashSet<JobWbsAssignments2>();
            this.ProjSiteAssignments = new HashSet<ProjSiteAssignment>();
            this.SiteConfigActions = new HashSet<SiteConfigAction>();
            this.SiteInfoValues = new HashSet<SiteInfoValue>();
            this.Applications = new HashSet<Application>();
            this.ApplicationGroups = new HashSet<ApplicationGroup>();
        }
    
        public int SiteID { get; set; }
        public string SiteAbbr { get; set; }
        public string SiteName { get; set; }
        public string SiteDescription { get; set; }
        public string EdeDrive { get; set; }
        public string EdeFileServername { get; set; }
        public string EdeFileServerSharename { get; set; }
        public Nullable<int> GBUID { get; set; }
        public string Comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppGroupSiteConfigAction> AppGroupSiteConfigActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppSiteConfigAction> AppSiteConfigActions { get; set; }
        public virtual GBU GBU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobWbsAssignments2> JobWbsAssignments2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjSiteAssignment> ProjSiteAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiteConfigAction> SiteConfigActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiteInfoValue> SiteInfoValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Applications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationGroup> ApplicationGroups { get; set; }
    }
}
